name: genforce
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pip
  - numpy
  - pip:
      - torchmetrics
      - torchdata
      - opencv-python
      - einops
      - open-clip-torch
      - clip @ git+https://github.com/openai/CLIP.git
      - transformers
      - urllib3
      - xformers
      - streamlit-keyup
      - diffusers
      - gradio
      - wandb
      - vision-aided-loss
      - clean-fid
      - dominate
      - lpips
      - peft
      - tokenizers
      - tqdm
      - taichi
      - pytransform3d
      - imageio
      - open3d
      - scikit-image
      - pillow
      - scipy
      - timm

